version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_appication
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://ecommerce_user:ecommerce_password@db:5432/ecommercedb

  db:
    image: postgres:15
    container_name: postgres_database
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password
      POSTGRES_DB: ecommercedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: